services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /myapp
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    command: bash -c "bundle install && rails server -b 0.0.0.0"
