services:
  web:
    build: .
    working_dir: /myapp
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    env_file:
      - .env
    tty: true
    command: bash -c "bin/rails server -b 0.0.0.0 -p 3000"
